language: python
dist: trusty
python:
  - 3.4
  - 3.5
notifications:
  email: false
addons:
  apt:
    packages:
        - libblas-dev
        - liblapack-dev
env:
    global:
        # Maximal dependencies
        - DEPENDS="cython numpy scipy matplotlib"
before_install:
  - source travis-tools/utils.sh
  - travis_before_install
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:marutter/c2d4u
  - sudo add-apt-repository -y ppa:marutter/rrutter
  - sudo apt-get update
  - sudo apt-get install -y r-base r-base-dev r-cran-devtools r-cran-rcpp


install:
  # Install selection
  - pip install traitlets
  - git submodule update --init 
  - cd R-selective
  - git submodule update --init 
  - sudo Rscript -e "install.packages(c('glmnet', 'intervals', 'adaptMCMC', 'gglasso', 'knockoff'), repos='http://cloud.r-project.org')"
  - sudo make install
  - cd ../regreg
  - pip install -r requirements.txt
  - pip install -e .
  - cd ../selective-inference
  - git submodule update --init 
  - pip install  -r requirements.txt; 
  - pip install -e .
  - cd ..

# command to run tests, e.g. python setup.py test
script:
    - python compare.py --all_methods_noR --rho 0 0.3 --csvfile blah3.csv --nsample 500 --nfeature 100 --nsignal 10 --signal 4 3 --htmlfile blue.html --verbose --nsim 5
    - python compare.py --all_methods_noR --wide_only --rho 0 --csvfile blah3.csv --nsample 400 --nfeature 500 --nsignal 10 --signal 3 --htmlfile blue.html --verbose --nsim 5

